
const characters_dict = {
    'Ironclad': {
        'max_hp': 80,
        'model': 'extra_trees_ironclad.pkl',
        'initial_cards': ['Strike_R','Strike_R','Strike_R','Strike_R','Strike_R', 'Defend_R','Defend_R','Defend_R','Defend_R','Bash'],
        'initial_relic': 'Burning Blood',
        'cards': {
            'Adrenaline': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e3/Adrenaline.png',
                'After Image': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/73/AfterImage.png',
                'Alpha': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/Alpha.png',
                'Anger': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3f/Anger.png',
                'Apotheosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Apotheosis.png',
                'Armaments': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c3/Armaments.png',
                'AscendersBane': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a0/Ascender%27s_Bane.png',
                'Backstab': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7a/Backstab.png',
                'Bandage Up': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/BandageUp.png',
                'Barricade': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/12/Barricade.png',
                'Bash': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d8/Bash.png',
                'Battle Trance': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3a/BattleTrance.png',
                'Beam Cell': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/BeamCell.png',
                'Berserk': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/Berserk.png',
                'Bite': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Bite.png',
                'Blade Dance': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/BladeDance.png',
                'Blind': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/68/Blind.png',
                'Blood for Blood': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c8/BloodforBlood.png',
                'Bloodletting': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/ff/Bloodletting.png',
                'Bludgeon': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/96/Bludgeon.png',
                'Body Slam': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/10/BodySlam.png',
                'Brutality': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/ba/Brutality.png',
                'Buffer': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/Buffer.png',
                'Carnage': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4f/Carnage.png',
                'Chaos': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8f/Chaos.png',
                'Chill': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7b/Chill.png',
                'Chrysalis': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/01/Chrysalis.png',
                'Clash': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fb/Clash.png',
                'Cleave': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c8/Cleave.png',
                'Cloak And Dagger': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3f/CloakAndDagger.png',
                'Clothesline': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8f/Clothesline.png',
                'Clumsy': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8e/Clumsy.png',
                'Combust': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e7/Combust.png',
                'Core Surge': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/49/CoreSurge.png',
                'Corpse Explosion': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/28/CorpseExplosion.png',
                'Corruption': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/75/Corruption.png',
                'Creative AI': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/CreativeAI.png',
                'Crescendo': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b1/Crescendo.png',
                'CrushJoints': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/34/CrushJoints.png',
                'CultistMask': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a3/CutThroughFate.png',
                'Dagger Spray': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/46/DaggerSpray.png',
                'Dark Embrace': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a6/DarkEmbrace.png',
                'Dark Shackles': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/79/DarkShackles.png',
                'Dash': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/55/Dash.png',
                'Decay': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Decay.png',
                'DeceiveReality': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c5/DeceiveReality.png',
                'Deep Breath': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/62/DeepBreath.png',
                'Defend_P': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Defend_P.png',
                'Defend_R': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7d/Defend_R.png',
                'Demon Form': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a1/DemonForm.png',
                'Devotion': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4b/Devotion.png',
                'Disarm': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Disarm.png',
                'Discovery': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/Discovery.png',
                'Doom and Gloom': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/87/DoomandGloom.png',
                'Doppelganger': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/75/Doppelganger.png',
                'Double Tap': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/84/DoubleTap.png',
                'Doubt': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6a/Doubt.png',
                'Dramatic Entrance': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/42/DramaticEntrance.png',
                'Dropkick': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/02/Dropkick.png',
                'Dual Wield': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/61/DualWield.png',
                'Echo Form': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/EchoForm.png',
                'Enlightenment': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/Enlightenment.png',
                'Entrench': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Entrench.png',
                'Escape Plan': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/EscapePlan.png',
                'Evolve': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5d/Evolve.png',
                'Exhume': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1b/Exhume.png',
                'Feed': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/Feed.png',
                'Feel No Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/41/FeelNoPain.png',
                'Fiend Fire': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0a/FiendFire.png',
                'Finesse': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/67/Finesse.png',
                'Fire Breathing': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/60/FireBreathing.png',
                'Flame Barrier': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cc/FlameBarrier.png',
                'Flash of Steel': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9c/FlashofSteel.png',
                'Flex': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/Flex.png',
                'Flying Knee': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/28/FlyingKnee.png',
                'Footwork': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/84/Footwork.png',
                'Forethought': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/Forethought.png',
                'Genetic Algorithm': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/GeneticAlgorithm.png',
                'Ghostly Armor': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/71/GhostlyArmor.png',
                'Glass Knife': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/62/GlassKnife.png',
                'Go for the Eyes': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/GofortheEyes.png',
                'Good Instincts': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/GoodInstincts.png',
                'HandOfGreed': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/HandOfGreed.png',
                'Havoc': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5b/Havoc.png',
                'Headbutt': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/Headbutt.png',
                'Heavy Blade': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/58/HeavyBlade.png',
                'Heel Hook': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/75/HeelHook.png',
                'Hemokinesis': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/17/Hemokinesis.png',
                'Hyperbeam': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f3/Hyperbeam.png',
                'Immolate': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5f/Immolate.png',
                'Impatience': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/Impatience.png',
                'Impervious': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e3/Impervious.png',
                'Infernal Blade': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0b/InfernalBlade.png',
                'Inflame': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/02/Inflame.png',
                'Injury': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Injury.png',
                'Intimidate': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/72/Intimidate.png',
                'Iron Wave': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9e/IronWave.png',
                'J.A.X.': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/J.A.X..png',
                'Jack Of All Trades': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d9/JackOfAllTrades.png',
                'Juggernaut': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/Juggernaut.png',
                'Leg Sweep': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/65/LegSweep.png',
                'Limit Break': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8c/LimitBreak.png',
                'Machine Learning': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/03/MachineLearning.png',
                'Madness': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ee/Madness.png',
                'Magnetism': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8d/Magnetism.png',
                'Mayhem': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/Mayhem.png',
                'Meditate': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/61/Meditate.png',
                'Metallicize': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Metallicize.png',
                'Metamorphosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Metamorphosis.png',
                'Meteor Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/15/MeteorStrike.png',
                'Mind Blast': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/26/MindBlast.png',
                'Necronomicon': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/Necronomicurse.png',
                'Night Terror': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9b/Nightmare.png',
                'Normality': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a5/Normality.png',
                'Offering': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/Offering.png',
                'Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/54/Pain.png',
                'Panacea': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/37/Panacea.png',
                'Panache': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/Panache.png',
                'PanicButton': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/PanicButton.png',
                'Parasite': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f0/Parasite.png',
                'Perfected Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/77/PerfectedStrike.png',
                'Perseverance': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7f/Perseverance.png',
                'PiercingWail': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0a/PiercingWail.png',
                'Poisoned Stab': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9e/PoisonedStab.png',
                'Pommel Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/35/PommelStrike.png',
                'Power Through': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4f/PowerThrough.png',
                'Predator': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e9/Predator.png',
                'Prepared': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/83/Prepared.png',
                'Protect': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f6/Protect.png',
                'Pummel': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ec/Pummel.png',
                'Purity': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Purity.png',
                'Rage': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Rage.png',
                'Ragnarok': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/68/Ragnarok.png',
                'Rampage': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e4/Rampage.png',
                'ReachHeaven': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8d/ReachHeaven.png',
                'Reaper': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6a/Reaper.png',
                'Rebound': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d0/Rebound.png',
                'Reckless Charge': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f7/RecklessCharge.png',
                'Regret': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Regret.png',
                'Reprogram': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9d/Reprogram.png',
                'Riddle With Holes': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/RiddleWithHoles.png',
                'Rupture': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/Rupture.png',
                'Sadistic Nature': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/SadisticNature.png',
                'SandsOfTime': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/SandsofTime.png',
                'Scrape': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/94/Scrape.png',
                'Scrawl': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/df/Scrawl.png',
                'Searing Blow': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dc/SearingBlow.png',
                'Second Wind': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/ba/SecondWind.png',
                'Secret Technique': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/SecretTechnique.png',
                'Secret Weapon': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/SecretWeapon.png',
                'Seeing Red': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c2/SeeingRed.png',
                'Self Repair': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b2/SelfRepair.png',
                'Sentinel': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/91/Sentinel.png',
                'Sever Soul': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/11/SeverSoul.png',
                'Shame': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/Shame.png',
                'Shockwave': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/65/Shockwave.png',
                'Shrug It Off': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4a/ShrugItOff.png',
                'SignatureMove': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a4/SignatureMove.png',
                'Skim': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/55/Skim.png',
                'Slice': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ad/Slice.png',
                'Spot Weakness': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/56/SpotWeakness.png',
                'Streamline': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/64/Streamline.png',
                'Strike_R': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/06/Strike_R.png',
                'Sucker Punch': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/89/SuckerPunch.png',
                'Sweeping Beam': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/ca/SweepingBeam.png',
                'Swift Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8b/SwiftStrike.png',
                'Sword Boomerang': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/18/SwordBoomerang.png',
                'The Bomb': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/69/TheBomb.png',
                'Thinking Ahead': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/ThinkingAhead.png',
                'Thunderclap': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8a/Thunderclap.png',
                'Tools of the Trade': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/db/ToolsoftheTrade.png',
                'Transmutation': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Transmutation.png',
                'Trip': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cf/Trip.png',
                'True Grit': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/46/TrueGrit.png',
                'Twin Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/18/TwinStrike.png',
                'Uppercut': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Uppercut.png',
                'Violence': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e4/Violence.png',
                'Warcry': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9a/Warcry.png',
                'WaveOfTheHand': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e7/WaveoftheHand.png',
                'Whirlwind': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e0/Whirlwind.png',
                'White Noise': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/WhiteNoise.png',
                'Wild Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/WildStrike.png',
                'Wraith Form v2': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ec/WraithForm.png',
                'Writhe': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6e/Writhe.png'
        }
    },
    'Silent': {
        'max_hp': 70,
        'model': 'extra_trees_silent.pkl',
        'initial_cards': ['Strike_G','Strike_G','Strike_G','Strike_G','Strike_G','Defend_G','Defend_G','Defend_G','Defend_G','Defend_G','Neutralize','Survivor'],
        'initial_relic': 'Ring of the Snake',
        'cards': {'A Thousand Cuts': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/52/AThousandCuts.png',
            'Accuracy': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/Accuracy.png',
            'Acrobatics': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/db/Acrobatics.png',
            'Adrenaline': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e3/Adrenaline.png',
            'After Image': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/73/AfterImage.png',
            'Apotheosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Apotheosis.png',
            'AscendersBane': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a0/Ascender%27s_Bane.png',
            'Backflip': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/74/Backflip.png',
            'Backstab': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7a/Backstab.png',
            'Bandage Up': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/BandageUp.png',
            'Bane': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9a/Bane.png',
            'Bash': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d8/Bash.png',
            'Battle Trance': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3a/BattleTrance.png',
            'BattleHymn': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/67/BattleHymn.png',
            'Bite': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Bite.png',
            'Blade Dance': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/BladeDance.png',
            'Blasphemy': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/22/Blasphemy.png',
            'Blind': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/68/Blind.png',
            'Bludgeon': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/96/Bludgeon.png',
            'Blur': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f4/Blur.png',
            'Bouncing Flask': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3c/BouncingFlask.png',
            'BowlingBash': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/BowlingBash.png',
            'Bullet Time': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1e/BulletTime.png',
            'Burst': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/Burst.png',
            'Calculated Gamble': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/89/CalculatedGamble.png',
            'Caltrops': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/31/Caltrops.png',
            'Catalyst': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b2/Catalyst.png',
            'Chill': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7b/Chill.png',
            'Choke': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/09/Choke.png',
            'Chrysalis': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/01/Chrysalis.png',
            'Cloak And Dagger': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3f/CloakAndDagger.png',
            'Clothesline': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8f/Clothesline.png',
            'Cold Snap': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/ColdSnap.png',
            'Concentrate': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Concentrate.png',
            'Core Surge': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/49/CoreSurge.png',
            'Corpse Explosion': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/28/CorpseExplosion.png',
            'Crippling Poison': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/15/CripplingCloud.png',
            'CultistMask': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a3/CutThroughFate.png',
            'Dagger Spray': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/46/DaggerSpray.png',
            'Dagger Throw': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3f/R_dagger-throw.png',
            'Dark Shackles': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/79/DarkShackles.png',
            'Dash': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/55/Dash.png',
            'Deadly Poison': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b7/DeadlyPoison.png',
            'Decay': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Decay.png',
            'Deep Breath': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/62/DeepBreath.png',
            'Defend_G': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/Defend_G.png',
            'Deflect': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Deflect.png',
            'Die Die Die': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/25/DieDieDie.png',
            'Discovery': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/Discovery.png',
            'Distraction': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e3/Distraction.png',
            'Dodge and Roll': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/09/DodgeandRoll.png',
            'Doppelganger': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/75/Doppelganger.png',
            'Doubt': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6a/Doubt.png',
            'Dramatic Entrance': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/42/DramaticEntrance.png',
            'Echo Form': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/EchoForm.png',
            'Endless Agony': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1e/EndlessAgony.png',
            'Enlightenment': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/Enlightenment.png',
            'Envenom': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/17/Envenom.png',
            'Escape Plan': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/EscapePlan.png',
            'Evaluate': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/59/Evaluate.png',
            'Eviscerate': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/Eviscerate.png',
            'Evolve': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5d/Evolve.png',
            'Expertise': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/Expertise.png',
            'FTL': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c6/FTL.png',
            'Fasting2': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fb/Fasting.png',
            'Feel No Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/41/FeelNoPain.png',
            'Finesse': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/67/Finesse.png',
            'Finisher': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/Finisher.png',
            'Flame Barrier': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cc/FlameBarrier.png',
            'Flash of Steel': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9c/FlashofSteel.png',
            'Flechettes': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cc/Flechettes.png',
            'Flex': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/Flex.png',
            'Flying Knee': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/28/FlyingKnee.png',
            'FollowUp': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/72/Follow-Up.png',
            'Footwork': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/84/Footwork.png',
            'Forethought': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/Forethought.png',
            'Glass Knife': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/62/GlassKnife.png',
            'Good Instincts': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/GoodInstincts.png',
            'Grand Finale': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/94/GrandFinale.png',
            'HandOfGreed': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/HandOfGreed.png',
            'Heel Hook': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/75/HeelHook.png',
            'Hyperbeam': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f3/Hyperbeam.png',
            'Impatience': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/Impatience.png',
            'Impervious': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e3/Impervious.png',
            'Infinite Blades': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cb/InfiniteBlades.png',
            'Injury': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Injury.png',
            'Iron Wave': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9e/IronWave.png',
            'J.A.X.': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/J.A.X..png',
            'Jack Of All Trades': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d9/JackOfAllTrades.png',
            'JustLucky': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/JustLucky.png',
            'Leg Sweep': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/65/LegSweep.png',
            'Machine Learning': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/03/MachineLearning.png',
            'Madness': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ee/Madness.png',
            'Magnetism': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8d/Magnetism.png',
            'Malaise': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d1/Malaise.png',
            'Masterful Stab': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/MasterfulStab.png',
            'Mayhem': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/Mayhem.png',
            'Metallicize': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Metallicize.png',
            'Metamorphosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Metamorphosis.png',
            'Mind Blast': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/26/MindBlast.png',
            'Necronomicon': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/Necronomicurse.png',
            'Neutralize': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c5/Neutralize.png',
            'Night Terror': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9b/Nightmare.png',
            'Normality': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a5/Normality.png',
            'Noxious Fumes': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/NoxiousFumes.png',
            'Outmaneuver': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/ff/Outmaneuver.png',
            'Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/54/Pain.png',
            'Panacea': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/37/Panacea.png',
            'Panache': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/Panache.png',
            'PanicButton': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/PanicButton.png',
            'Parasite': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f0/Parasite.png',
            'Perfected Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/77/PerfectedStrike.png',
            'Phantasmal Killer': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/87/PhantasmalKiller.png',
            'PiercingWail': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0a/PiercingWail.png',
            'Poisoned Stab': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9e/PoisonedStab.png',
            'Pommel Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/35/PommelStrike.png',
            'Predator': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e9/Predator.png',
            'Prepared': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/83/Prepared.png',
            'Protect': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f6/Protect.png',
            'Purity': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Purity.png',
            'Quick Slash': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f5/QuickSlash.png',
            'Rage': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Rage.png',
            'Reboot': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/de/Reboot.png',
            'Recycle': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/70/Recycle.png',
            'Reflex': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b2/Reflex.png',
            'Regret': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Regret.png',
            'Reprogram': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9d/Reprogram.png',
            'Riddle With Holes': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/RiddleWithHoles.png',
            'Sadistic Nature': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/SadisticNature.png',
            'Secret Technique': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/SecretTechnique.png',
            'Secret Weapon': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/SecretWeapon.png',
            'Setup': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/98/Setup.png',
            'Shame': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/Shame.png',
            'Skewer': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/Skewer.png',
            'Slice': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ad/Slice.png',
            'Storm of Steel': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/bd/StormofSteel.png',
            'Strike_G': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3d/Strike_G.png',
            'Sucker Punch': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/89/SuckerPunch.png',
            'Survivor': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/Survivor.png',
            'Swift Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8b/SwiftStrike.png',
            'Swivel': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/21/Swivel.png',
            'Tactician': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/77/Tactician.png',
            'Terror': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cc/Terror.png',
            'The Bomb': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/69/TheBomb.png',
            'Thinking Ahead': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/ThinkingAhead.png',
            'Tools of the Trade': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/db/ToolsoftheTrade.png',
            'Transmutation': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Transmutation.png',
            'Trip': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cf/Trip.png',
            'Unload': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f0/Unload.png',
            'Uppercut': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Uppercut.png',
            'Violence': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e4/Violence.png',
            'Well Laid Plans': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/85/Well-LaidPlans.png',
            'WheelKick': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/86/WheelKick.png',
            'Wraith Form v2': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ec/WraithForm.png',
            'Writhe': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6e/Writhe.png'}
    },
    'Defect': {
        'max_hp': 75,
        'model': 'extra_trees_defect.pkl',
        'initial_cards': ['Strike_B','Strike_B','Strike_B','Strike_B','Defend_B','Defend_B','Defend_B','Defend_B','Zap','Dualcast'],
        'initial_relic': 'Cracked Core',
        'cards': {'Aggregate': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/Aggregate.png',
            'Amplify': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/Amplify.png',
            'Apotheosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Apotheosis.png',
            'AscendersBane': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a0/Ascender%27s_Bane.png',
            'Backflip': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/74/Backflip.png',
            'Ball Lightning': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b7/BallLightning.png',
            'Bandage Up': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/BandageUp.png',
            'Barrage': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/2c/Barrage.png',
            'Barricade': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/12/Barricade.png',
            'Beam Cell': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/BeamCell.png',
            'Berserk': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/Berserk.png',
            'Biased Cognition': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/50/BiasedCognition.png',
            'Bite': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Bite.png',
            'Blade Dance': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/BladeDance.png',
            'Blind': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/68/Blind.png',
            'Blizzard': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/39/Blizzard.png',
            'Body Slam': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/10/BodySlam.png',
            'BootSequence': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/BootSequence.png',
            'Buffer': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/Buffer.png',
            'Caltrops': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/31/Caltrops.png',
            'Capacitor': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b5/Capacitor.png',
            'Chaos': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8f/Chaos.png',
            'Chill': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7b/Chill.png',
            'Chrysalis': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/01/Chrysalis.png',
            'Clash': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fb/Clash.png',
            'Cleave': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c8/Cleave.png',
            'Clumsy': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8e/Clumsy.png',
            'Cold Snap': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/ColdSnap.png',
            'Collect': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/84/Collect.png',
            'Compile Driver': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c5/CompileDriver.png',
            'Consume': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b6/Consume.png',
            'Coolheaded': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e7/Coolheaded.png',
            'Core Surge': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/49/CoreSurge.png',
            'Creative AI': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/CreativeAI.png',
            'CultistMask': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a3/CutThroughFate.png',
            'Dagger Throw': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3f/R_dagger-throw.png',
            'Dark Shackles': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/79/DarkShackles.png',
            'Darkness': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c0/Darkness.png',
            'Deadly Poison': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b7/DeadlyPoison.png',
            'Decay': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Decay.png',
            'Deep Breath': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/62/DeepBreath.png',
            'Defend_B': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/71/Defend_B.png',
            'Deflect': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Deflect.png',
            'Defragment': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/Defragment.png',
            'DeusExMachina': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b6/DeusExMachina.png',
            'Discovery': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/Discovery.png',
            'Distraction': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e3/Distraction.png',
            'Dodge and Roll': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/09/DodgeandRoll.png',
            'Doom and Gloom': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/87/DoomandGloom.png',
            'Double Energy': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/46/DoubleEnergy.png',
            'Double Tap': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/84/DoubleTap.png',
            'Doubt': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6a/Doubt.png',
            'Dramatic Entrance': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/42/DramaticEntrance.png',
            'Dual Wield': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/61/DualWield.png',
            'Dualcast': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/00/Dualcast.png',
            'Echo Form': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/EchoForm.png',
            'Electrodynamics': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/ff/Electrodynamics.png',
            'Enlightenment': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/Enlightenment.png',
            'Envenom': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/17/Envenom.png',
            'Establishment': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5b/Establishment.png',
            'Evaluate': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/59/Evaluate.png',
            'FTL': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c6/FTL.png',
            'Finesse': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/67/Finesse.png',
            'Fission': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4d/Fission.png',
            'Flash of Steel': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9c/FlashofSteel.png',
            'Flex': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/Flex.png',
            'Flying Knee': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/28/FlyingKnee.png',
            'Force Field': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/aa/ForceField.png',
            'Forethought': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/Forethought.png',
            'Fusion': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/2d/Fusion.png',
            'Genetic Algorithm': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/GeneticAlgorithm.png',
            'Glacier': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/24/Glacier.png',
            'Go for the Eyes': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/GofortheEyes.png',
            'Good Instincts': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/GoodInstincts.png',
            'HandOfGreed': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/HandOfGreed.png',
            'Headbutt': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/Headbutt.png',
            'Heatsinks': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0b/Heatsinks.png',
            'Hello World': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f3/HelloWorld.png',
            'Hologram': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3b/Hologram-0.png',
            'Hyperbeam': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f3/Hyperbeam.png',
            'Impatience': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/Impatience.png',
            'Infernal Blade': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0b/InfernalBlade.png',
            'Infinite Blades': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cb/InfiniteBlades.png',
            'Injury': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Injury.png',
            'Iron Wave': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9e/IronWave.png',
            'J.A.X.': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/J.A.X..png',
            'Jack Of All Trades': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d9/JackOfAllTrades.png',
            'Leap': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/af/Leap.png',
            'Leg Sweep': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/65/LegSweep.png',
            'Loop': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/21/Loop.png',
            'Machine Learning': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/03/MachineLearning.png',
            'Madness': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ee/Madness.png',
            'Magnetism': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8d/Magnetism.png',
            'Malaise': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d1/Malaise.png',
            'Mayhem': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/Mayhem.png',
            'Melter': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/71/Melter.png',
            'Metamorphosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Metamorphosis.png',
            'Meteor Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/15/MeteorStrike.png',
            'Mind Blast': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/26/MindBlast.png',
            'Multi-Cast': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/91/Multi-Cast.png',
            'Necronomicon': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/Necronomicurse.png',
            'Night Terror': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9b/Nightmare.png',
            'Normality': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a5/Normality.png',
            'Noxious Fumes': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/NoxiousFumes.png',
            'Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/54/Pain.png',
            'Panacea': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/37/Panacea.png',
            'Panache': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/Panache.png',
            'PanicButton': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/PanicButton.png',
            'Parasite': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f0/Parasite.png',
            'PiercingWail': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0a/PiercingWail.png',
            'Pommel Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/35/PommelStrike.png',
            'Protect': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f6/Protect.png',
            'Purity': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Purity.png',
            'Quick Slash': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f5/QuickSlash.png',
            'Rainbow': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1e/Rainbow.png',
            'Reboot': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/de/Reboot.png',
            'Rebound': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d0/Rebound.png',
            'Recycle': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/70/Recycle.png',
            'Regret': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Regret.png',
            'Reinforced Body': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d4/ReinforcedBody.png',
            'Reprogram': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9d/Reprogram.png',
            'Rip and Tear': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/13/RipandTear.png',
            'Sadistic Nature': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/SadisticNature.png',
            'Scrape': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/94/Scrape.png',
            'Secret Technique': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/SecretTechnique.png',
            'Secret Weapon': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/SecretWeapon.png',
            'Seek': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/72/Seek.png',
            'Self Repair': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b2/SelfRepair.png',
            'Shame': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/Shame.png',
            'Skewer': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/Skewer.png',
            'Skim': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/55/Skim.png',
            'Slice': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ad/Slice.png',
            'Stack': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/Stack.png',
            'Static Discharge': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/StaticDischarge.png',
            'Storm': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/Storm.png',
            'Streamline': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/64/Streamline.png',
            'Strike_B': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/16/Strike_B.png',
            'Sucker Punch': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/89/SuckerPunch.png',
            'Sunder': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/60/Sunder.png',
            'Survivor': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/Survivor.png',
            'Sweeping Beam': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/ca/SweepingBeam.png',
            'Swift Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8b/SwiftStrike.png',
            'Tempest': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/bb/Tempest.png',
            'The Bomb': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/69/TheBomb.png',
            'Thinking Ahead': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/ThinkingAhead.png',
            'Thunder Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c8/ThunderStrike.png',
            'Thunderclap': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8a/Thunderclap.png',
            'Transmutation': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Transmutation.png',
            'Trip': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cf/Trip.png',
            'True Grit': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/46/TrueGrit.png',
            'Violence': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e4/Violence.png',
            'White Noise': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/WhiteNoise.png',
            'Writhe': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6e/Writhe.png',
            'Zap': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0b/Zap.png'}
    },
    'Watcher': {
        'max_hp': 75,
        'model': 'extra_trees_watcher.pkl',
        'initial_cards': ['Strike_P','Strike_P','Strike_P','Strike_P','Defend_P','Defend_P','Defend_P','Defend_P','Eruption', 'Vigilance','AscendersBane'],
        'initial_relic': 'Pure Water',
        'cards': {'Alpha': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/Alpha.png',
            'Apotheosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Apotheosis.png',
            'AscendersBane': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a0/Ascender%27s_Bane.png',
            'Ball Lightning': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b7/BallLightning.png',
            'Bandage Up': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/BandageUp.png',
            'BattleHymn': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/67/BattleHymn.png',
            'Bite': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/29/Bite.png',
            'Blasphemy': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/22/Blasphemy.png',
            'Blind': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/68/Blind.png',
            'BowlingBash': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/BowlingBash.png',
            'Brilliance': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/Brilliance.png',
            'Burst': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/47/Burst.png',
            'CarveReality': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/CarveReality.png',
            'Chrysalis': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/01/Chrysalis.png',
            'Collect': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/84/Collect.png',
            'Conclude': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e1/Conclude.png',
            'ConjureBlade': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/35/ConjureBlade.png',
            'Consecrate': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c2/Consecrate.png',
            'Crescendo': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b1/Crescendo.png',
            'CrushJoints': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/34/CrushJoints.png',
            'CultistMask': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a3/CutThroughFate.png',
            'Dark Shackles': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/79/DarkShackles.png',
            'Decay': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Decay.png',
            'DeceiveReality': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c5/DeceiveReality.png',
            'Deep Breath': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/62/DeepBreath.png',
            'Defend_P': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Defend_P.png',
            'DeusExMachina': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b6/DeusExMachina.png',
            'Devotion': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4b/Devotion.png',
            'Discovery': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/Discovery.png',
            'Doubt': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6a/Doubt.png',
            'Dramatic Entrance': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/42/DramaticEntrance.png',
            'EmptyBody': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4f/EmptyBody.png',
            'EmptyFist': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/76/EmptyFist.png',
            'EmptyMind': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/35/EmptyMind.png',
            'Enlightenment': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/Enlightenment.png',
            'Eruption': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/52/Eruption.png',
            'Establishment': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5b/Establishment.png',
            'Evaluate': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/59/Evaluate.png',
            'Fasting2': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fb/Fasting.png',
            'FearNoEvil': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/49/FearNoEvil.png',
            'Finesse': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/67/Finesse.png',
            'Flash of Steel': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9c/FlashofSteel.png',
            'Flex': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/Flex.png',
            'FlurryOfBlows': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/28/FlurryOfBlows.png',
            'FlyingSleeves': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/77/FlyingSleeves.png',
            'FollowUp': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/72/Follow-Up.png',
            'ForeignInfluence': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c8/ForeignInfluence.png',
            'Forethought': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/88/Forethought.png',
            'Genetic Algorithm': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/GeneticAlgorithm.png',
            'Good Instincts': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b8/GoodInstincts.png',
            'Halt': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/09/Halt.png',
            'HandOfGreed': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/HandOfGreed.png',
            'Impatience': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/Impatience.png',
            'Indignation': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8b/Indignation.png',
            'Injury': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Injury.png',
            'InnerPeace': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8f/InnerPeace.png',
            'Iron Wave': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9e/IronWave.png',
            'J.A.X.': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/J.A.X..png',
            'Jack Of All Trades': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d9/JackOfAllTrades.png',
            'JustLucky': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/JustLucky.png',
            'LessonLearned': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/LessonLearned.png',
            'LikeWater': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/99/LikeWater.png',
            'Madness': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ee/Madness.png',
            'Magnetism': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8d/Magnetism.png',
            'MasterReality': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c8/MasterReality.png',
            'Mayhem': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dd/Mayhem.png',
            'Meditate': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/61/Meditate.png',
            'MentalFortress': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c1/MentalFortress.png',
            'Metamorphosis': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/Metamorphosis.png',
            'Mind Blast': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/26/MindBlast.png',
            'Nirvana': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/37/Nirvana.png',
            'Normality': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a5/Normality.png',
            'Omniscience': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a1/Omniscience.png',
            'Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/54/Pain.png',
            'Panacea': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/37/Panacea.png',
            'Panache': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/19/Panache.png',
            'PanicButton': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/08/PanicButton.png',
            'Parasite': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f0/Parasite.png',
            'Perseverance': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7f/Perseverance.png',
            'Pray': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Pray.png',
            'Prostrate': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b2/Prostrate.png',
            'Protect': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f6/Protect.png',
            'Purity': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/Purity.png',
            'Ragnarok': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/68/Ragnarok.png',
            'ReachHeaven': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8d/ReachHeaven.png',
            'Regret': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Regret.png',
            'Riddle With Holes': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d5/RiddleWithHoles.png',
            'Sadistic Nature': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a8/SadisticNature.png',
            'Sanctity': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/71/Sanctity.png',
            'SandsOfTime': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/SandsofTime.png',
            'SashWhip': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4a/SashWhip.png',
            'Scrawl': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/df/Scrawl.png',
            'Secret Technique': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/SecretTechnique.png',
            'Secret Weapon': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5a/SecretWeapon.png',
            'Shame': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/Shame.png',
            'Shrug It Off': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4a/ShrugItOff.png',
            'SignatureMove': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a4/SignatureMove.png',
            'SpiritShield': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/52/SpiritShield.png',
            'Stack': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/Stack.png',
            'Strike_P': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5e/Strike_P.png',
            'Study': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/26/Study.png',
            'Swift Strike': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8b/SwiftStrike.png',
            'Swivel': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/21/Swivel.png',
            'TalkToTheHand': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f8/TalktotheHand.png',
            'Tantrum': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b3/Tantrum.png',
            'The Bomb': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/69/TheBomb.png',
            'Thinking Ahead': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0c/ThinkingAhead.png',
            'Transmutation': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cd/Transmutation.png',
            'Trip': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/cf/Trip.png',
            'Vault': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c9/Vault.png',
            'Vigilance': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d3/Vigilance.png',
            'Violence': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e4/Violence.png',
            'Wallop': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/27/Wallop.png',
            'WaveOfTheHand': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e7/WaveoftheHand.png',
            'Weave': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/63/Weave.png',
            'WheelKick': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/86/WheelKick.png',
            'WindmillStrike': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/aa/WindmillStrike.png',
            'Wish': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f3/Wish.png',
            'Worship': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d4/Worship.png',
            'WreathOfFlame': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d8/WreathofFlame.png',
            'Writhe': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6e/Writhe.png'}
    }
}