const relics_dict = {'Akabeko': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/Akabeko.png',
    'Anchor': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c0/Anchor.png',
    'Ancient Tea Set': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e6/AncientTeaSet.png',
    'Art of War': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/bb/ArtofWar.png',
    'Bag of Marbles': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f5/BagofMarbles.png',
    'Bag of Preparation': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ad/BagofPreparation.png',
    'Bird Faced Urn': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/BirdFacedUrn.png',
    'Black Blood': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/32/BlackBlood.png',
    'Black Star': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/10/BlackStar.png',
    'Blood Vial': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4e/BloodVial.png',
    'Bloody Idol': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/61/BloodyIdol.png',
    'Blue Candle': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1b/BlueCandle.png',
    'Bottled Flame': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f1/BottledFlame.png',
    'Bottled Lightning': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a9/BottledLightning.png',
    'Bottled Tornado': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ac/BottledTornado.png',
    'Brimstone': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/25/Brimstone.png',
    'Bronze Scales': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3e/BronzeScales.png',
    'Burning Blood': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/BurningBlood.png',
    'Busted Crown': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f7/BustedCrown.png',
    'Calipers': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ed/Calipers.png',
    'Calling Bell': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/56/CallingBell.png',
    'CaptainsWheel': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a6/Captain_wheel.png',
    'Cauldron': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/37/Cauldron.png',
    'Centennial Puzzle': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0f/CentennialPuzzle.png',
    'CeramicFish': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a1/CeramicFish.png',
    'Champion Belt': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/ChampionBelt.png',
    "Charon's Ashes": 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ea/CharonsAshes.png',
    'Chemical X': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f9/ChemicalX.png',
    'CloakClasp': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6a/CloakClasp.png',
    'ClockworkSouvenir': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d9/ClockworkSouvenir.png',
    'Coffee Dripper': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/86/CoffeeDripper.png',
    'Cracked Core': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ed/CrackedCore.png',
    'Cursed Key': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e0/CursedKey.png',
    'Damaru': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/20/Damaru.png',
    'Darkstone Periapt': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5c/DarkstonePeriapt.png',
    'DataDisk': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b1/DataDisk.png',
    'Dead Branch': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/db/DeadBranch.png',
    'Dream Catcher': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d3/DreamCatcher.png',
    'Du-Vu Doll': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/79/Du-VuDoll.png',
    'Ectoplasm': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/36/Ectoplasm.png',
    'Emotion Chip': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dc/EmotionChip.png',
    'Empty Cage': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/64/EmptyCage.png',
    'Enchiridion': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8e/Enchiridion.png',
    'Eternal Feather': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f4/EternalFeather.png',
    'FaceOfCleric': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9d/FaceOfCleric.png',
    'FossilizedHelix': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/25/FossilizedHelix.png',
    'FrozenCore': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1d/FrozenCore.png',
    'Fusion Hammer': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/31/FusionHammer.png',
    'Gambling Chip': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/GamblingChip.png',
    'Ginger': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/85/Ginger.png',
    'Girya': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/92/Girya.png',
    'Golden Eye': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b7/Golden_eye.png',
    'Golden Idol': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/58/GoldenIdol.png',
    'GremlinMask': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/GremlinMask.png',
    'HandDrill': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d0/HandDrill.png',
    'Happy Flower': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7a/HappyFlower.png',
    'HornCleat': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/bb/Horn_cleat.png',
    'HoveringKite': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/96/HoveringKite.png',
    'Ice Cream': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/14/IceCream.png',
    'Incense Burner': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/78/IncenseBurner.png',
    'InkBottle': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a3/InkBottle.png',
    'Inserter': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fd/Inserter.png',
    'Kunai': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d7/Kunai.png',
    'Lantern': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f5/Lantern.png',
    "Lee's Waffle": 'https://static.wikia.nocookie.net/slay-the-spire/images/0/03/LeesWaffle.png',
    'Letter Opener': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e5/LetterOpener.png',
    'Lizard Tail': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ae/LizardTail.png',
    'Magic Flower': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0e/MagicFlower.png',
    'Mango': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/Mango.png',
    'Mark of Pain': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/df/MarkofPain.png',
    'Mark of the Bloom': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0b/MarkoftheBloom.png',
    'Matryoshka': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7a/Matryoshka.png',
    'Maw Bank': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e4/MawBank.png',
    'MealTicket': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/13/MealTicket.png',
    'Meat on the Bone': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/04/MeatontheBone.png',
    'Medical Kit': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f2/MedicalKit.png',
    'Melange': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3a/Melange.png',
    'Membership Card': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/3d/MembershipCard.png',
    'Mercury Hourglass': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/32/MercuryHourglass.png',
    'Molten Egg 2': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/76/MoltenEgg2.png',
    'Mummified Hand': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4d/MummifiedHand.png',
    'MutagenicStrength': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/2a/MutagenicStrength.png',
    'NeowsBlessing': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/63/NeowsBlessing.png',
    "Nilry's Codex": 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e2/NilrysCodex.png',
    'Ninja Scroll': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/81/NinjaScroll.png',
    'Nuclear Battery': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4c/NuclearBattery.png',
    'Nunchaku': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7d/Nunchaku.png',
    'Odd Mushroom': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a0/OddMushroom.png',
    'Oddly Smooth Stone': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ec/OddlySmoothStone.png',
    'Old Coin': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/38/OldCoin.png',
    'Omamori': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/Omamori.png',
    'Orange Pellets': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/OrangePellets.png',
    'Orichalcum': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/80/Orichalcum.png',
    'Ornamental Fan': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/52/OrnamentalFan.png',
    'Orrery': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/75/Orrery.png',
    'Pantograph': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/82/Pantograph.png',
    'Paper Crane': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c0/PaperCrane.png',
    'Paper Frog': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/99/PaperFrog.png',
    'Peace Pipe': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/26/PeacePipe.png',
    'Pear': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b0/Pear.png',
    'Pen Nib': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/70/PenNib.png',
    "Philosopher's Stone": 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1a/PhilosophersStone.png',
    'Pocketwatch': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1c/Pocketwatch.png',
    'Potion Belt': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/94/PotionBelt.png',
    'Prayer Wheel': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/1f/PrayerWheel.png',
    'PreservedInsect': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/ef/PreservedInsect.png',
    'PrismaticShard': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c9/PrismaticShard.png',
    'PureWater': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/fa/PureWater-0.png',
    'Question Card': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6e/QuestionCard.png',
    'Red Mask': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a4/RedMask.png',
    'Red Skull': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/4f/RedSkull.png',
    'Regal Pillow': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9d/RegalPillow.png',
    'Ring of the Serpent': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/58/RingoftheSerpent.png',
    'Ring of the Snake': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/90/RingoftheSnake.png',
    'Runic Capacitor': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/59/RunicCapacitor.png',
    'Runic Cube': 'https://static.wikia.nocookie.net/slay-the-spire/images/3/36/RunicCube.png',
    'Runic Dome': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/RunicDome.png',
    'Runic Pyramid': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8e/RunicPyramid.png',
    'SacredBark': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/SacredBark.png',
    'Self Forming Clay': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/24/SelfFormingClay.png',
    'Shovel': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/77/Shovel.png',
    'Shuriken': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/ac/Shuriken.png',
    'Singing Bowl': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/eb/SingingBowl.png',
    'SlaversCollar': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/99/SlaversCollar.png',
    'Sling': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/93/Sling.png',
    'Smiling Mask': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/48/SmilingMask.png',
    'Snake Skull': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/d7/SnakeSkull.png',
    'Snecko Eye': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5e/SneckoEye.png',
    'Sozu': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/53/Sozu.png',
    'Spirit Poop': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/74/SpiritPoop.png',
    'Ssserpent Head': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a2/SsserpentHead.png',
    'StoneCalendar': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/50/StoneCalendar.png',
    'Strange Spoon': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/71/StrangeSpoon.png',
    'Strawberry': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6d/Strawberry.png',
    'StrikeDummy': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/df/StrikeDummy.png',
    'Sundial': 'https://static.wikia.nocookie.net/slay-the-spire/images/1/15/Sundial.png',
    'Symbiotic Virus': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/0f/SymbioticVirus.png',
    'TeardropLocket': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/44/Tear_drop_locket.png',
    'TheAbacus': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9a/TheAbacus.png',
    'Thread and Needle': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/87/ThreadandNeedle.png',
    'Tingsha': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/78/Tingsha.png',
    'Tiny Chest': 'https://static.wikia.nocookie.net/slay-the-spire/images/6/6b/TinyChest.png',
    'Tiny House': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/53/TinyHouse.png',
    'Toolbox': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/46/Toolbox.png',
    'Torii': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/23/Torii.png',
    'Tough Bandages': 'https://static.wikia.nocookie.net/slay-the-spire/images/f/f7/ToughBandages.png',
    'Toxic Egg 2': 'https://static.wikia.nocookie.net/slay-the-spire/images/c/c4/ToxicEgg2.png',
    'Toy Ornithopter': 'https://static.wikia.nocookie.net/slay-the-spire/images/2/2b/ToyOrnithopter.png',
    'TungstenRod': 'https://static.wikia.nocookie.net/slay-the-spire/images/a/a3/TungstenRod.png',
    'Turnip': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b7/Turnip.png',
    'TwistedFunnel': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/7e/TwistedFunnel.png',
    'Unceasing Top': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/06/UnceasingTop.png',
    'Vajra': 'https://static.wikia.nocookie.net/slay-the-spire/images/d/dc/Vajra.png',
    'Velvet Choker': 'https://static.wikia.nocookie.net/slay-the-spire/images/b/b9/VelvetChoker.png',
    'VioletLotus': 'https://static.wikia.nocookie.net/slay-the-spire/images/8/8b/Violet_lotus.png',
    'War Paint': 'https://static.wikia.nocookie.net/slay-the-spire/images/0/07/WarPaint.png',
    'WarpedTongs': 'https://static.wikia.nocookie.net/slay-the-spire/images/4/41/WarpedTongs.png',
    'Whetstone': 'https://static.wikia.nocookie.net/slay-the-spire/images/9/9f/Whetstone.png',
    'White Beast Statue': 'https://static.wikia.nocookie.net/slay-the-spire/images/5/5b/WhiteBeastStatue.png',
    'WingedGreaves': 'https://static.wikia.nocookie.net/slay-the-spire/images/7/70/WingedGreaves.png',
    'Wrist Blade': 'https://static.wikia.nocookie.net/slay-the-spire/images/e/e0/WristBlade.png'}